import './globals.css';
import { Inter } from 'next/font/google';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Script src="https://momentjs.com/downloads/moment-timezone-with-data-10-year-range.js" /> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
